version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/html

hooks:
  ApplicationStart:
    - location: /bin/bash
      timeout: 300
      runas: ubuntu
      script: "sudo cp /var/www/html/index.html /var/www/html/index.html"
